[project]
name = "recruiterlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "github3-py>=4.0.1",
    "pygithub>=2.5.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.391",
]
